name: codersMojoBackend CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: coders-mojo-backend-prod
        environment_name: coders-mojo-backend-prod-env
        version_label: 12345
        region: ap-southeast-1
        deployment_package: deploy.zip
