name: deploy aws eb staging CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn

      - name: Run deploy-aws-eb-staging.sh
        run: sh deploy-aws-eb-staging.sh